### ISSUE TITLE
BUG: 会将网络错误识别成标签已经存在

### ISSUE THREAD

**Issue by fjwxzde** [DuckDuckStudio/GitHub-Labels-Manager#22]

**Comment by DuckDuckStudio** [comment]
https://docs.github.com/zh/rest/issues/labels?apiVersion=2022-11-28#create-a-label--status-codes

**Comment by fjwxzde** [comment]
可否添加一些其他检测以区分？
重复时的返回信息似乎不一样。

**Comment by DuckDuckStudio** [comment]
将在 v1.4 中修复
