### ISSUE TITLE
[Docs] GLM已有英语程序，但缺少英语文档

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/GitHub-Labels-Manager#9]
@fjwxzde set
@Luna-Grace 可以帮忙翻译下吗？

**Comment by fjwxzde** [comment]
> [!WARNING]
> 设置失败：422

**Comment by Luna-Grace** [comment]
之前已在 27b71add9e293a612cadab208cdb6e83d37566cf 中尝试自动翻译，但效果不理想。
这可能代表这个文档需要手动翻译。

**Comment by Luna-Grace** [comment]
自动翻译总是把`repository`翻译成`warehouse`（😂）

**Comment by DuckDuckStudio** [comment]
此文档将在v1.3及以后版本中添加进英文发行版程序中
